spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apro
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

apro:
  jwt:
    key: ${JWT_KEY}
    access:
      expiration: ${ACCESS_EXP}
      header: ${ACCESS_HEADER}
    refresh:
      expiration: ${REFRESH_EXP}
      header: ${REFRESH_HEADER}

logging:
  level:
    root: info
